//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuZhouCivilAffairs.MongoDBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EndUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnduserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SimCardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuZhouCivilAffairs.MongoDBService.ArrayOfString IdentitiesField;
        
        private System.DateTime LastModifyTimeField;
        
        private bool IsValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AutoID {
            get {
                return this.AutoIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoIDField, value) != true)) {
                    this.AutoIDField = value;
                    this.RaisePropertyChanged("AutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EnduserName {
            get {
                return this.EnduserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnduserNameField, value) != true)) {
                    this.EnduserNameField = value;
                    this.RaisePropertyChanged("EnduserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SimCardNo {
            get {
                return this.SimCardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SimCardNoField, value) != true)) {
                    this.SimCardNoField = value;
                    this.RaisePropertyChanged("SimCardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public QuZhouCivilAffairs.MongoDBService.ArrayOfString Identities {
            get {
                return this.IdentitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentitiesField, value) != true)) {
                    this.IdentitiesField = value;
                    this.RaisePropertyChanged("Identities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime LastModifyTime {
            get {
                return this.LastModifyTimeField;
            }
            set {
                if ((this.LastModifyTimeField.Equals(value) != true)) {
                    this.LastModifyTimeField = value;
                    this.RaisePropertyChanged("LastModifyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MongoDBService.MongoDBServiceSoap")]
    public interface MongoDBServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 newUser 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEnduser", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.InsertEnduserResponse InsertEnduser(QuZhouCivilAffairs.MongoDBService.InsertEnduserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 newUsers 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndusers", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.InsertEndusersResponse InsertEndusers(QuZhouCivilAffairs.MongoDBService.InsertEndusersRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SelectAllResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.SelectAllResponse SelectAll(QuZhouCivilAffairs.MongoDBService.SelectAllRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 msg 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountAll", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.CountAllResponse CountAll(QuZhouCivilAffairs.MongoDBService.CountAllRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 iSimCardNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectEnduserBySimCardNo", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoResponse SelectEnduserBySimCardNo(QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 iAutoID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectEnduserByAutoID", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDResponse SelectEnduserByAutoID(QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 iEnduserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectEnduserByName", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameResponse SelectEnduserByName(QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 iSimCardNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEnduser", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.DeleteEnduserResponse DeleteEnduser(QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 newUser 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEnduser", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.UpdateEnduserResponse UpdateEnduser(QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 newUsers 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEndusers", ReplyAction="*")]
        QuZhouCivilAffairs.MongoDBService.UpdateEndusersResponse UpdateEndusers(QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEnduserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEnduser", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.InsertEnduserRequestBody Body;
        
        public InsertEnduserRequest() {
        }
        
        public InsertEnduserRequest(QuZhouCivilAffairs.MongoDBService.InsertEnduserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEnduserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser newUser;
        
        public InsertEnduserRequestBody() {
        }
        
        public InsertEnduserRequestBody(QuZhouCivilAffairs.MongoDBService.EndUser newUser) {
            this.newUser = newUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEnduserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEnduserResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.InsertEnduserResponseBody Body;
        
        public InsertEnduserResponse() {
        }
        
        public InsertEnduserResponse(QuZhouCivilAffairs.MongoDBService.InsertEnduserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEnduserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertEnduserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public InsertEnduserResponseBody() {
        }
        
        public InsertEnduserResponseBody(bool InsertEnduserResult, string msg) {
            this.InsertEnduserResult = InsertEnduserResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndusersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndusers", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.InsertEndusersRequestBody Body;
        
        public InsertEndusersRequest() {
        }
        
        public InsertEndusersRequest(QuZhouCivilAffairs.MongoDBService.InsertEndusersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndusersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser[] newUsers;
        
        public InsertEndusersRequestBody() {
        }
        
        public InsertEndusersRequestBody(QuZhouCivilAffairs.MongoDBService.EndUser[] newUsers) {
            this.newUsers = newUsers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndusersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndusersResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.InsertEndusersResponseBody Body;
        
        public InsertEndusersResponse() {
        }
        
        public InsertEndusersResponse(QuZhouCivilAffairs.MongoDBService.InsertEndusersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndusersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertEndusersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public InsertEndusersResponseBody() {
        }
        
        public InsertEndusersResponseBody(bool InsertEndusersResult, string msg) {
            this.InsertEndusersResult = InsertEndusersResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAll", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectAllRequestBody Body;
        
        public SelectAllRequest() {
        }
        
        public SelectAllRequest(QuZhouCivilAffairs.MongoDBService.SelectAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllRequestBody {
        
        public SelectAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectAllResponseBody Body;
        
        public SelectAllResponse() {
        }
        
        public SelectAllResponse(QuZhouCivilAffairs.MongoDBService.SelectAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser[] SelectAllResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SelectAllResponseBody() {
        }
        
        public SelectAllResponseBody(QuZhouCivilAffairs.MongoDBService.EndUser[] SelectAllResult, string msg) {
            this.SelectAllResult = SelectAllResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountAll", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.CountAllRequestBody Body;
        
        public CountAllRequest() {
        }
        
        public CountAllRequest(QuZhouCivilAffairs.MongoDBService.CountAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CountAllRequestBody {
        
        public CountAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.CountAllResponseBody Body;
        
        public CountAllResponse() {
        }
        
        public CountAllResponse(QuZhouCivilAffairs.MongoDBService.CountAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long CountAllResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public CountAllResponseBody() {
        }
        
        public CountAllResponseBody(long CountAllResult, string msg) {
            this.CountAllResult = CountAllResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectEnduserBySimCardNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectEnduserBySimCardNo", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequestBody Body;
        
        public SelectEnduserBySimCardNoRequest() {
        }
        
        public SelectEnduserBySimCardNoRequest(QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectEnduserBySimCardNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iSimCardNo;
        
        public SelectEnduserBySimCardNoRequestBody() {
        }
        
        public SelectEnduserBySimCardNoRequestBody(string iSimCardNo) {
            this.iSimCardNo = iSimCardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectEnduserBySimCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectEnduserBySimCardNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoResponseBody Body;
        
        public SelectEnduserBySimCardNoResponse() {
        }
        
        public SelectEnduserBySimCardNoResponse(QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectEnduserBySimCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser SelectEnduserBySimCardNoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SelectEnduserBySimCardNoResponseBody() {
        }
        
        public SelectEnduserBySimCardNoResponseBody(QuZhouCivilAffairs.MongoDBService.EndUser SelectEnduserBySimCardNoResult, string msg) {
            this.SelectEnduserBySimCardNoResult = SelectEnduserBySimCardNoResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectEnduserByAutoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectEnduserByAutoID", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequestBody Body;
        
        public SelectEnduserByAutoIDRequest() {
        }
        
        public SelectEnduserByAutoIDRequest(QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectEnduserByAutoIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iAutoID;
        
        public SelectEnduserByAutoIDRequestBody() {
        }
        
        public SelectEnduserByAutoIDRequestBody(string iAutoID) {
            this.iAutoID = iAutoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectEnduserByAutoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectEnduserByAutoIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDResponseBody Body;
        
        public SelectEnduserByAutoIDResponse() {
        }
        
        public SelectEnduserByAutoIDResponse(QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectEnduserByAutoIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser SelectEnduserByAutoIDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SelectEnduserByAutoIDResponseBody() {
        }
        
        public SelectEnduserByAutoIDResponseBody(QuZhouCivilAffairs.MongoDBService.EndUser SelectEnduserByAutoIDResult, string msg) {
            this.SelectEnduserByAutoIDResult = SelectEnduserByAutoIDResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectEnduserByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectEnduserByName", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequestBody Body;
        
        public SelectEnduserByNameRequest() {
        }
        
        public SelectEnduserByNameRequest(QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectEnduserByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iEnduserName;
        
        public SelectEnduserByNameRequestBody() {
        }
        
        public SelectEnduserByNameRequestBody(string iEnduserName) {
            this.iEnduserName = iEnduserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectEnduserByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectEnduserByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameResponseBody Body;
        
        public SelectEnduserByNameResponse() {
        }
        
        public SelectEnduserByNameResponse(QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectEnduserByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser[] SelectEnduserByNameResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public SelectEnduserByNameResponseBody() {
        }
        
        public SelectEnduserByNameResponseBody(QuZhouCivilAffairs.MongoDBService.EndUser[] SelectEnduserByNameResult, string msg) {
            this.SelectEnduserByNameResult = SelectEnduserByNameResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEnduserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEnduser", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequestBody Body;
        
        public DeleteEnduserRequest() {
        }
        
        public DeleteEnduserRequest(QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEnduserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iSimCardNo;
        
        public DeleteEnduserRequestBody() {
        }
        
        public DeleteEnduserRequestBody(string iSimCardNo) {
            this.iSimCardNo = iSimCardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEnduserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEnduserResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.DeleteEnduserResponseBody Body;
        
        public DeleteEnduserResponse() {
        }
        
        public DeleteEnduserResponse(QuZhouCivilAffairs.MongoDBService.DeleteEnduserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEnduserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteEnduserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public DeleteEnduserResponseBody() {
        }
        
        public DeleteEnduserResponseBody(bool DeleteEnduserResult, string msg) {
            this.DeleteEnduserResult = DeleteEnduserResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEnduserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEnduser", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequestBody Body;
        
        public UpdateEnduserRequest() {
        }
        
        public UpdateEnduserRequest(QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEnduserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser newUser;
        
        public UpdateEnduserRequestBody() {
        }
        
        public UpdateEnduserRequestBody(QuZhouCivilAffairs.MongoDBService.EndUser newUser) {
            this.newUser = newUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEnduserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEnduserResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.UpdateEnduserResponseBody Body;
        
        public UpdateEnduserResponse() {
        }
        
        public UpdateEnduserResponse(QuZhouCivilAffairs.MongoDBService.UpdateEnduserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEnduserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateEnduserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public UpdateEnduserResponseBody() {
        }
        
        public UpdateEnduserResponseBody(bool UpdateEnduserResult, string msg) {
            this.UpdateEnduserResult = UpdateEnduserResult;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEndusersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEndusers", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequestBody Body;
        
        public UpdateEndusersRequest() {
        }
        
        public UpdateEndusersRequest(QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEndusersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuZhouCivilAffairs.MongoDBService.EndUser[] newUsers;
        
        public UpdateEndusersRequestBody() {
        }
        
        public UpdateEndusersRequestBody(QuZhouCivilAffairs.MongoDBService.EndUser[] newUsers) {
            this.newUsers = newUsers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEndusersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEndusersResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuZhouCivilAffairs.MongoDBService.UpdateEndusersResponseBody Body;
        
        public UpdateEndusersResponse() {
        }
        
        public UpdateEndusersResponse(QuZhouCivilAffairs.MongoDBService.UpdateEndusersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEndusersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateEndusersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public UpdateEndusersResponseBody() {
        }
        
        public UpdateEndusersResponseBody(bool UpdateEndusersResult, string msg) {
            this.UpdateEndusersResult = UpdateEndusersResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MongoDBServiceSoapChannel : QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MongoDBServiceSoapClient : System.ServiceModel.ClientBase<QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap>, QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap {
        
        public MongoDBServiceSoapClient() {
        }
        
        public MongoDBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MongoDBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MongoDBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MongoDBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.InsertEnduserResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.InsertEnduser(QuZhouCivilAffairs.MongoDBService.InsertEnduserRequest request) {
            return base.Channel.InsertEnduser(request);
        }
        
        public bool InsertEnduser(QuZhouCivilAffairs.MongoDBService.EndUser newUser, out string msg) {
            QuZhouCivilAffairs.MongoDBService.InsertEnduserRequest inValue = new QuZhouCivilAffairs.MongoDBService.InsertEnduserRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.InsertEnduserRequestBody();
            inValue.Body.newUser = newUser;
            QuZhouCivilAffairs.MongoDBService.InsertEnduserResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).InsertEnduser(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.InsertEnduserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.InsertEndusersResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.InsertEndusers(QuZhouCivilAffairs.MongoDBService.InsertEndusersRequest request) {
            return base.Channel.InsertEndusers(request);
        }
        
        public bool InsertEndusers(QuZhouCivilAffairs.MongoDBService.EndUser[] newUsers, out string msg) {
            QuZhouCivilAffairs.MongoDBService.InsertEndusersRequest inValue = new QuZhouCivilAffairs.MongoDBService.InsertEndusersRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.InsertEndusersRequestBody();
            inValue.Body.newUsers = newUsers;
            QuZhouCivilAffairs.MongoDBService.InsertEndusersResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).InsertEndusers(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.InsertEndusersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.SelectAllResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.SelectAll(QuZhouCivilAffairs.MongoDBService.SelectAllRequest request) {
            return base.Channel.SelectAll(request);
        }
        
        public QuZhouCivilAffairs.MongoDBService.EndUser[] SelectAll(out string msg) {
            QuZhouCivilAffairs.MongoDBService.SelectAllRequest inValue = new QuZhouCivilAffairs.MongoDBService.SelectAllRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.SelectAllRequestBody();
            QuZhouCivilAffairs.MongoDBService.SelectAllResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).SelectAll(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SelectAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.CountAllResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.CountAll(QuZhouCivilAffairs.MongoDBService.CountAllRequest request) {
            return base.Channel.CountAll(request);
        }
        
        public long CountAll(out string msg) {
            QuZhouCivilAffairs.MongoDBService.CountAllRequest inValue = new QuZhouCivilAffairs.MongoDBService.CountAllRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.CountAllRequestBody();
            QuZhouCivilAffairs.MongoDBService.CountAllResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).CountAll(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.CountAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.SelectEnduserBySimCardNo(QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequest request) {
            return base.Channel.SelectEnduserBySimCardNo(request);
        }
        
        public QuZhouCivilAffairs.MongoDBService.EndUser SelectEnduserBySimCardNo(string iSimCardNo, out string msg) {
            QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequest inValue = new QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoRequestBody();
            inValue.Body.iSimCardNo = iSimCardNo;
            QuZhouCivilAffairs.MongoDBService.SelectEnduserBySimCardNoResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).SelectEnduserBySimCardNo(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SelectEnduserBySimCardNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.SelectEnduserByAutoID(QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequest request) {
            return base.Channel.SelectEnduserByAutoID(request);
        }
        
        public QuZhouCivilAffairs.MongoDBService.EndUser SelectEnduserByAutoID(string iAutoID, out string msg) {
            QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequest inValue = new QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDRequestBody();
            inValue.Body.iAutoID = iAutoID;
            QuZhouCivilAffairs.MongoDBService.SelectEnduserByAutoIDResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).SelectEnduserByAutoID(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SelectEnduserByAutoIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.SelectEnduserByName(QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequest request) {
            return base.Channel.SelectEnduserByName(request);
        }
        
        public QuZhouCivilAffairs.MongoDBService.EndUser[] SelectEnduserByName(string iEnduserName, out string msg) {
            QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequest inValue = new QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameRequestBody();
            inValue.Body.iEnduserName = iEnduserName;
            QuZhouCivilAffairs.MongoDBService.SelectEnduserByNameResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).SelectEnduserByName(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.SelectEnduserByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.DeleteEnduserResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.DeleteEnduser(QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequest request) {
            return base.Channel.DeleteEnduser(request);
        }
        
        public bool DeleteEnduser(string iSimCardNo, out string msg) {
            QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequest inValue = new QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.DeleteEnduserRequestBody();
            inValue.Body.iSimCardNo = iSimCardNo;
            QuZhouCivilAffairs.MongoDBService.DeleteEnduserResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).DeleteEnduser(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.DeleteEnduserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.UpdateEnduserResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.UpdateEnduser(QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequest request) {
            return base.Channel.UpdateEnduser(request);
        }
        
        public bool UpdateEnduser(QuZhouCivilAffairs.MongoDBService.EndUser newUser, out string msg) {
            QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequest inValue = new QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.UpdateEnduserRequestBody();
            inValue.Body.newUser = newUser;
            QuZhouCivilAffairs.MongoDBService.UpdateEnduserResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).UpdateEnduser(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.UpdateEnduserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuZhouCivilAffairs.MongoDBService.UpdateEndusersResponse QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap.UpdateEndusers(QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequest request) {
            return base.Channel.UpdateEndusers(request);
        }
        
        public bool UpdateEndusers(QuZhouCivilAffairs.MongoDBService.EndUser[] newUsers, out string msg) {
            QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequest inValue = new QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequest();
            inValue.Body = new QuZhouCivilAffairs.MongoDBService.UpdateEndusersRequestBody();
            inValue.Body.newUsers = newUsers;
            QuZhouCivilAffairs.MongoDBService.UpdateEndusersResponse retVal = ((QuZhouCivilAffairs.MongoDBService.MongoDBServiceSoap)(this)).UpdateEndusers(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.UpdateEndusersResult;
        }
    }
}
