//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Interface
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class quzhoucivilaffairsEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“quzhoucivilaffairsEntities”部分中的连接字符串初始化新 quzhoucivilaffairsEntities 对象。
        /// </summary>
        public quzhoucivilaffairsEntities() : base("name=quzhoucivilaffairsEntities", "quzhoucivilaffairsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 quzhoucivilaffairsEntities 对象。
        /// </summary>
        public quzhoucivilaffairsEntities(string connectionString) : base(connectionString, "quzhoucivilaffairsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 quzhoucivilaffairsEntities 对象。
        /// </summary>
        public quzhoucivilaffairsEntities(EntityConnection connection) : base(connection, "quzhoucivilaffairsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cms_content> cms_content
        {
            get
            {
                if ((_cms_content == null))
                {
                    _cms_content = base.CreateObjectSet<cms_content>("cms_content");
                }
                return _cms_content;
            }
        }
        private ObjectSet<cms_content> _cms_content;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<column> column
        {
            get
            {
                if ((_column == null))
                {
                    _column = base.CreateObjectSet<column>("column");
                }
                return _column;
            }
        }
        private ObjectSet<column> _column;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 cms_content EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocms_content(cms_content cms_content)
        {
            base.AddObject("cms_content", cms_content);
        }
    
        /// <summary>
        /// 用于向 column EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocolumn(column column)
        {
            base.AddObject("column", column);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quzhoucivilaffairsModel", Name="cms_content")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cms_content : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cms_content 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="author">author 属性的初始值。</param>
        /// <param name="cid">cid 属性的初始值。</param>
        /// <param name="columnId">columnId 属性的初始值。</param>
        public static cms_content Createcms_content(global::System.String id, global::System.String author, global::System.String cid, global::System.String columnId)
        {
            cms_content cms_content = new cms_content();
            cms_content.id = id;
            cms_content.author = author;
            cms_content.cid = cid;
            cms_content.columnId = columnId;
            return cms_content;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cid
        {
            get
            {
                return _cid;
            }
            set
            {
                OncidChanging(value);
                ReportPropertyChanging("cid");
                _cid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cid");
                OncidChanged();
            }
        }
        private global::System.String _cid;
        partial void OncidChanging(global::System.String value);
        partial void OncidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String columnId
        {
            get
            {
                return _columnId;
            }
            set
            {
                OncolumnIdChanging(value);
                ReportPropertyChanging("columnId");
                _columnId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("columnId");
                OncolumnIdChanged();
            }
        }
        private global::System.String _columnId;
        partial void OncolumnIdChanging(global::System.String value);
        partial void OncolumnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pics
        {
            get
            {
                return _pics;
            }
            set
            {
                OnpicsChanging(value);
                ReportPropertyChanging("pics");
                _pics = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pics");
                OnpicsChanged();
            }
        }
        private global::System.String _pics;
        partial void OnpicsChanging(global::System.String value);
        partial void OnpicsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String published
        {
            get
            {
                return _published;
            }
            set
            {
                OnpublishedChanging(value);
                ReportPropertyChanging("published");
                _published = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("published");
                OnpublishedChanged();
            }
        }
        private global::System.String _published;
        partial void OnpublishedChanging(global::System.String value);
        partial void OnpublishedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String summary
        {
            get
            {
                return _summary;
            }
            set
            {
                OnsummaryChanging(value);
                ReportPropertyChanging("summary");
                _summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("summary");
                OnsummaryChanged();
            }
        }
        private global::System.String _summary;
        partial void OnsummaryChanging(global::System.String value);
        partial void OnsummaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String top
        {
            get
            {
                return _top;
            }
            set
            {
                OntopChanging(value);
                ReportPropertyChanging("top");
                _top = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("top");
                OntopChanged();
            }
        }
        private global::System.String _top;
        partial void OntopChanging(global::System.String value);
        partial void OntopChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="quzhoucivilaffairsModel", Name="column")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class column : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 column 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static column Createcolumn(global::System.String id)
        {
            column column = new column();
            column.id = id;
            return column;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alias
        {
            get
            {
                return _alias;
            }
            set
            {
                OnaliasChanging(value);
                ReportPropertyChanging("alias");
                _alias = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("alias");
                OnaliasChanged();
            }
        }
        private global::System.String _alias;
        partial void OnaliasChanging(global::System.String value);
        partial void OnaliasChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String desc
        {
            get
            {
                return _desc;
            }
            set
            {
                OndescChanging(value);
                ReportPropertyChanging("desc");
                _desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("desc");
                OndescChanged();
            }
        }
        private global::System.String _desc;
        partial void OndescChanging(global::System.String value);
        partial void OndescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private Nullable<global::System.Int32> _pid;
        partial void OnpidChanging(Nullable<global::System.Int32> value);
        partial void OnpidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prop
        {
            get
            {
                return _prop;
            }
            set
            {
                OnpropChanging(value);
                ReportPropertyChanging("prop");
                _prop = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prop");
                OnpropChanged();
            }
        }
        private global::System.String _prop;
        partial void OnpropChanging(global::System.String value);
        partial void OnpropChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sid
        {
            get
            {
                return _sid;
            }
            set
            {
                OnsidChanging(value);
                ReportPropertyChanging("sid");
                _sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sid");
                OnsidChanged();
            }
        }
        private Nullable<global::System.Int32> _sid;
        partial void OnsidChanging(Nullable<global::System.Int32> value);
        partial void OnsidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();

        #endregion

    
    }

    #endregion

    
}
